/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bpsk_squelch.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3a07e66be4916809d077add417d289b1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncdsss/bpsk_squelch.h>
// pydoc.h is automatically generated in the build directory
#include <bpsk_squelch_pydoc.h>

void bind_bpsk_squelch(py::module& m)
{

    using bpsk_squelch    = gr::ncdsss::bpsk_squelch;


    py::class_<bpsk_squelch, gr::block, gr::basic_block,
        std::shared_ptr<bpsk_squelch>>(m, "bpsk_squelch", D(bpsk_squelch))

        .def(py::init(&bpsk_squelch::make),
           D(bpsk_squelch,make)
        )
        



        ;




}








