/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(char_Resampler.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2c02dd7628ecdc5fd9d3050b54c61252)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncdsss/char_Resampler.h>
// pydoc.h is automatically generated in the build directory
#include <char_Resampler_pydoc.h>

void bind_char_Resampler(py::module& m)
{

    using char_Resampler    = ::gr::ncdsss::char_Resampler;


    py::class_<char_Resampler, gr::block, gr::basic_block,
        std::shared_ptr<char_Resampler>>(m, "char_Resampler", D(char_Resampler))

        .def(py::init(&char_Resampler::make),
           py::arg("symbol") = 3069000,
           py::arg("data") = 16384,
           D(char_Resampler,make)
        )
        



        ;




}








