/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(DSSS_Decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(98970c3627ecf740281f45c116ab868b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncdsss/DSSS_Decoder.h>
// pydoc.h is automatically generated in the build directory
#include <DSSS_Decoder_pydoc.h>

void bind_DSSS_Decoder(py::module& m)
{

    using DSSS_Decoder    = gr::ncdsss::DSSS_Decoder;


    py::class_<DSSS_Decoder, gr::block, gr::basic_block,
        std::shared_ptr<DSSS_Decoder>>(m, "DSSS_Decoder", D(DSSS_Decoder))

        .def(py::init(&DSSS_Decoder::make),
           D(DSSS_Decoder,make)
        )
        



        ;




}








