/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(DSSS_Encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d963f5372bcc56b3caa1ef25b3748ff4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ncdsss/DSSS_Encoder.h>
// pydoc.h is automatically generated in the build directory
#include <DSSS_Encoder_pydoc.h>

void bind_DSSS_Encoder(py::module& m)
{

    using DSSS_Encoder    = ::gr::ncdsss::DSSS_Encoder;


    py::class_<DSSS_Encoder, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<DSSS_Encoder>>(m, "DSSS_Encoder", D(DSSS_Encoder))

        .def(py::init(&DSSS_Encoder::make),
           py::arg("x1"),
           py::arg("x2"),
           py::arg("n1"),
           py::arg("n2"),
           D(DSSS_Encoder,make)
        )
        



        ;




}








